
## Python 

In [7]:
print("Hello python ")

Hello python 


In [8]:
name="murugan"
marks=100.0
print("My name is",name,"and my mark is",marks)
print()
print("My name is %s and my marks is %2f"%(name ,marks))
print()
print("My name is {} and my marks is {}".format(name,marks))

My name is murugan and my mark is 100.0

My name is murugan and my marks is 100.000000

My name is murugan and my marks is 100.0


In [9]:
a=10
b=20
c=a+b
print(c)

30


In [10]:
b=10.5
type(b)


float

In [12]:
z=int(input("Enter any number "))
z=abs(z)
print(z)
print(abs(z))

Enter any number 66
66
66


In [13]:
# complex
c= 5+3j
print(type(c))

#binary 

de=0b1010
print(de)

# hexadecimal 
v=0xff
print(v)


#octal 
ve=0O10
print(ve)

<class 'complex'>
10
255
8


In [14]:
a="Murugan"
type(a)

str

In [15]:
a=10
b=20
c=a+b
print(c)

30


In [16]:
a=input("Enter 1st number ")


Enter 1st number 8


In [17]:
type(a)

str

In [18]:
a=int(input("Enter 1st number "))
b=int(input("Enter 2nd number "))
print(a+b)

Enter 1st number 7
Enter 2nd number 8
15


### operators 

1. Arithmetic (+,-,*,/,**,//,%)
2. Assignment (=,+=,-=,*=,/=,**=,//=,%=)
3. Comparision (==,!=,<,>,<=,>=) --> give boolean output(TRUE/FALSE)
4. Logical (and,or,not )

In [19]:
# Logical 
x=5
y=10

print(x==5 and y==10)

True


In [20]:
#swapping
a=8
b=9
print(a)
temp=a


a=b
b=temp
print(a)

8
9


In [21]:
import random
random.randint(1,100)

75

In [22]:
a=int(input("Enter any number "))
if a==10:
    print("sucess")
else:
    print("failure")

Enter any number 999
failure


In [23]:
while True:
    a=int(input("Enter any number "))
    if a==10:
        print("sucess")
    else:
        print("failure")

Enter any number hh


ValueError: invalid literal for int() with base 10: 'hh'

In [24]:
for i in range(5):
    a=int(input("Enter any number "))
    if a==10:
        print("sucess")
    else:
        print("failure")

Enter any number 88
failure
Enter any number 99
failure
Enter any number 00
failure
Enter any number 99
failure
Enter any number 00
failure


In [25]:
for i in range(1,4):
    a =input("enter your pwd")
    if (a=="gokul"):
        print("Matched")
        break
    else:
        print("try again")
        continue
        
if (i==3):
    print("You tried more than 3 times.")

enter your pwdk
try again
enter your pwdii
try again
enter your pwd99
try again
You tried more than 3 times.


In [2]:
i=0
while (i<3):
    a=input("Enter your password : " )
    if a=="abcd":
        print("Password matched ")
        break
    else:
        print("Wrong password , Pls try again ")
        i=i+1     
if i==3:
    print("Sorry You Tried more than 3 times")
else:
    print("Sucessfully open the door ")  

Enter your password : abcd
Password matched 
Sucessfully open the door 


In [26]:
for i in range(10):
    i=i+1
    if i==5:
        continue
    else:
        print(i)

1
2
3
4
6
7
8
9
10


In [27]:
a="Murugan"
print(a)


Murugan


In [28]:
a[0:3]

'Mur'

In [29]:
a[4:7]

'gan'

In [30]:
a[0:7:2]

'Mrgn'

In [31]:
a[::-1]

'naguruM'

In [32]:
a= "nagalakshmi "
print(a.strip())
print(a.isalpha())
print(a.isnumeric())
print(a*2)

nagalakshmi
False
False
nagalakshmi nagalakshmi 


In [33]:
b="3534564"
print(b)
print(b.isnumeric())

3534564
True


In [34]:
l=["murugan",8,9,15,'a',10]
print(l)

['murugan', 8, 9, 15, 'a', 10]


In [35]:
l[0:3]

['murugan', 8, 9]

In [36]:
len(l)

6

In [37]:
cc=[1,2,3,4,5,8]
print(max(cc))
print(min(cc))
print(cc.sort())
print(cc)
print(cc.sort(reverse=True))
print(cc)

8
1
None
[1, 2, 3, 4, 5, 8]
None
[8, 5, 4, 3, 2, 1]


In [38]:
l.append("vit")

In [39]:
print(l)

['murugan', 8, 9, 15, 'a', 10, 'vit']


In [40]:
l.insert(2,"Vit")

In [41]:
l

['murugan', 8, 'Vit', 9, 15, 'a', 10, 'vit']

In [42]:
l.remove("murugan")

print(l)

In [43]:
print(l)

[8, 'Vit', 9, 15, 'a', 10, 'vit']


In [44]:
l.append("Vit")

In [45]:
l

[8, 'Vit', 9, 15, 'a', 10, 'vit', 'Vit']

In [46]:
l.count("Vit")

2

### Dictonary {}

In [47]:
#Dictonary 
d={}
D=dict()

In [48]:
d={'a':'apple','b':'ball','age':28,2:"hello"}
print(d)
print(d['a'])
print(d[2])

{'a': 'apple', 'b': 'ball', 'age': 28, 2: 'hello'}
apple
hello


In [49]:
print(d)
print(d.keys())
print(d.values())
print(d.items())

{'a': 'apple', 'b': 'ball', 'age': 28, 2: 'hello'}
dict_keys(['a', 'b', 'age', 2])
dict_values(['apple', 'ball', 28, 'hello'])
dict_items([('a', 'apple'), ('b', 'ball'), ('age', 28), (2, 'hello')])


In [50]:
d1={'a':'apple','b':'ball','age':28,2:"hello",'a':'app'}
str(d1)
print(d1)


{'a': 'app', 'b': 'ball', 'age': 28, 2: 'hello'}


In [51]:
# Python program to sort the items alphabetically from given dictionary 
  
# initialising _dictionary  
dict = {'key1' : 'AGeek', 'key2' : 'For', 'key3': 'IsGeeks',  'key4': 'ZGeeks'}  
  
# printing iniial_dictionary  
print ("Original dictionary", str(dict))  
  
# getting items in sorted order  
print ("\nItems in sorted order")  
for key in sorted(dict):  
    print (dict[key]) 
    

Original dictionary {'key1': 'AGeek', 'key2': 'For', 'key3': 'IsGeeks', 'key4': 'ZGeeks'}

Items in sorted order
AGeek
For
IsGeeks
ZGeeks


In [52]:
# Sort dictionary based on keys 

languages = {'Python': 93, 'Java': 95, 'C': 91, 'C++':92}
for key in sorted(languages.keys()) :
        print('%s : %s' %(key, languages[key]))
        


C : 91
C++ : 92
Java : 95
Python : 93


In [53]:
languages = {'Python': 93, 'Java': 95, 'C': 91, 'C++':92}
for key in sorted(languages.keys(),  reverse=True) :
        print('%s : %s' %(key, languages[key]))

Python : 93
Java : 95
C++ : 92
C : 91


In [54]:
# Sort dictionary based on values


languages = {'Python': 93, 'Java': 95, 'C': 91, 'C++':92}
for key, value in sorted(languages.items(),  key=lambda x:x[1]) :
        print('%s : %s' %(key, value))

C : 91
C++ : 92
Python : 93
Java : 95


In [55]:

dic = {3: 'Three',4:'Four',1:'One',2:'Two'} 
print(dic)
sorted_d1=sorted(dic)
print(sorted_d1)

for k in sorted (dic.keys()):
    print(k,dic[k])

{3: 'Three', 4: 'Four', 1: 'One', 2: 'Two'}
[1, 2, 3, 4]
1 One
2 Two
3 Three
4 Four


In [56]:
#swaping dict
d1={'a':'apple','b':'bat',2:'two',3:'three'}
d2={}
print(d1)
for k,v in d1.items():
    print(k,v)
    d2.update({v:k})
print(d2)


{'a': 'apple', 'b': 'bat', 2: 'two', 3: 'three'}
a apple
b bat
2 two
3 three
{'apple': 'a', 'bat': 'b', 'two': 2, 'three': 3}


In [57]:
res = dict((v,k) for k,v in a.items())

AttributeError: 'str' object has no attribute 'items'

In [58]:
d['name']="murugan"
print(d)
d['name']='bala'
print(d)

{'a': 'apple', 'b': 'ball', 'age': 28, 2: 'hello', 'name': 'murugan'}
{'a': 'apple', 'b': 'ball', 'age': 28, 2: 'hello', 'name': 'bala'}


In [59]:
print(d)
print(d.keys())
print(d.values())
print(d.items())

{'a': 'apple', 'b': 'ball', 'age': 28, 2: 'hello', 'name': 'bala'}
dict_keys(['a', 'b', 'age', 2, 'name'])
dict_values(['apple', 'ball', 28, 'hello', 'bala'])
dict_items([('a', 'apple'), ('b', 'ball'), ('age', 28), (2, 'hello'), ('name', 'bala')])


In [60]:
for k,v in d.items():
    print(k,v)

a apple
b ball
age 28
2 hello
name bala


In [61]:
d[2]="hello"
d

{'a': 'apple', 'b': 'ball', 'age': 28, 2: 'hello', 'name': 'bala'}

In [62]:
d.pop(2)   # delete 
print(d)

{'a': 'apple', 'b': 'ball', 'age': 28, 'name': 'bala'}


In [63]:
del d[2]

KeyError: 2

In [64]:
d.popitem()   # removes the last items . like pop in List 

('name', 'bala')

In [65]:
print(d)

{'a': 'apple', 'b': 'ball', 'age': 28}


In [66]:
d.update({'c':'cricket','m':'movie'})
d

{'a': 'apple', 'b': 'ball', 'age': 28, 'c': 'cricket', 'm': 'movie'}

In [74]:
d={}
k=input("enter your name ")
v=input("enter your DOB ")
d[k]=v
print(d)

enter your name sds
enter your DOB dsd
{'sds': 'dsd'}


In [75]:

dict = {'key1':'geeks', 'key2':'for'} 
print("Current Dict is: ", dict) 
  
# adding key3 
k=input("enter your name ")
v=input("enter your DOB ")
dict.update({k:v}) 
print("Updated Dict is: ", dict)

Current Dict is:  {'key1': 'geeks', 'key2': 'for'}
enter your name df
enter your DOB ds
Updated Dict is:  {'key1': 'geeks', 'key2': 'for', 'df': 'ds'}


In [76]:
k=input("enter your name ")
v=input("enter your DOB ")
dict.update({k:v}) 
print("Updated Dict is: ", dict)

enter your name sf
enter your DOB sdf
Updated Dict is:  {'key1': 'geeks', 'key2': 'for', 'df': 'ds', 'sf': 'sdf'}


In [77]:
Dict = {'Tim': 18,'Charlie':12,'Tiffany':22,'Robert':25}
Boys = {'Tim': 18,'Charlie':12,'Robert':25}
Girls = {'Tiffany':22}
for key in list(Dict.keys()):
    if key in list(Boys.keys()):
        print(True)
    else:       
        print(False)

TypeError: 'list' object is not callable

In [78]:
Dict = {'Tim': 18,'Charlie':12,'Tiffany':22,'Robert':25}
Boys = {'Tim': 18,'Charlie':12,'Robert':25}
Girls = {'Tiffany':22}
for key in Dict.keys():
    if key in Boys.keys():
        print(True)
    else:       
        print(False)

True
True
False
True


In [79]:
Dict = {'Tim': 18,'Charlie':12,'Tiffany':22,'Robert':25}
Boys = {'Tim': 18,'Charlie':12,'Robert':25}
for key in Dict.keys():
    for keys in Boys.keys():
        if key in keys:
            print(True)
        else:
            print(False)

True
False
False
False
True
False
False
False
False
False
False
True


In [81]:
dict={}
while 1:
    a=int(input("press update for 1 and  Search for 0 "))
    if a==1:
        k=input("Enter your name : ")
        v=input("enter your age ")
        dict.update({k:v}) 
        print("Updated Dict is: ", dict)
        continue
    elif a==0:
        ke=input("Enter your key name : ")
        print("your Key value  is: ", dict[ke])
        continue
    else:
        print("Your press wrong number  ")
        break


press update for 1 and  Search for 0 1
Enter your name : murugan
enter your age 13
Updated Dict is:  {'murugan': '13'}
press update for 1 and  Search for 0 5
Your press wrong number  


In [82]:
# Python program to sort the list  
# alphabetically in a dictionary 
dict ={ 
    "L1":[87, 34, 56, 12], 
    "L2":[23, 00, 30, 10], 
    "L3":[1, 6, 2, 9], 
    "L4":[40, 34, 21, 67] 
} 
  
print("\nBefore Sorting: ") 
for x in dict.items(): 
    print(x) 
  
print("\nAfter Sorting: ") 
  
for i, j in dict.items(): 
    sorted_dict ={i:sorted(j)} 
    print(sorted_dict) 


Before Sorting: 
('L1', [87, 34, 56, 12])
('L2', [23, 0, 30, 10])
('L3', [1, 6, 2, 9])
('L4', [40, 34, 21, 67])

After Sorting: 
{'L1': [12, 34, 56, 87]}
{'L2': [0, 10, 23, 30]}
{'L3': [1, 2, 6, 9]}
{'L4': [21, 34, 40, 67]}


## python comprehension tutorial

#### syntax :  
    [expr for element in iterable if condition]

In [83]:
#USING FOR LOOP
evens = []
for i in range(10):
   if i % 2 == 0:
      evens. append(i)
print(evens)

[0, 2, 4, 6, 8]


In [84]:
[i for i in range(10) if i % 2 ==0]

[0, 2, 4, 6, 8]

In [85]:
a="My name is 7 Murugan 8 and good "
b=a.split()
print(b)

['My', 'name', 'is', '7', 'Murugan', '8', 'and', 'good']


In [86]:
c=[]
for i in b :
    if i.isdigit():
        c.append(int(i))
print(c)

[7, 8]


In [87]:
[int(i) for i in b if i.isdigit()]

[7, 8]

In [88]:
#a=ini_string = "123()#$ABGFDabcjw"
a= "123()#$ABGFDabcjw"
#isalpha()
c=[]
for i in a:
    if i.isalpha():
            c.append(str(i))
print(c)
a="".join(c)
print(str(a))

['A', 'B', 'G', 'F', 'D', 'a', 'b', 'c', 'j', 'w']
ABGFDabcjw


In [90]:
# Your list with duplicate values using SET function 
duplicates = [1, 2, 3, 1, 2, 5, 6, 7, 8]

# Print the unique `duplicates` list
print(list(set(duplicates)))

TypeError: 'list' object is not callable

In [21]:
a=ini_string = "123()#$ABGFDabcjw"

" ".join(a.split())

'123()#$ABGFDabcjw'

In [64]:
#print not vowls in the sentences 
sen='hai how are you '
v='aeiou'
clear_sen=[]
for i in sen:
    if i not in v:
        clear_sen.append(i)
print("".join(clear_sen))

h hw r y 


In [66]:
sen='hai how are you '
v='aeiou'
"".join([i for i in sen if i not in v])


'h hw r y '

In [1]:
sen='hai how are you '
v='aeiou'
"".join((i for i in sen if i not in v))

'h hw r y '

In [68]:
country = ['India', 'Pakistan', 'Nepal', 'Bhutan', 'China', 'Bangladesh']
capital = ['New Delhi', 'Islamabad','Kathmandu', 'Thimphu', 'Beijing', 'Dhaka']

dic = {}
for i in range(len(country)):
    dic[country[i]] = capital[i]
print(dic)

{'India': 'New Delhi', 'Pakistan': 'Islamabad', 'Nepal': 'Kathmandu', 'Bhutan': 'Thimphu', 'China': 'Beijing', 'Bangladesh': 'Dhaka'}


In [69]:
{ country[i] : capital[i] for i in range(len(country)) }

{'India': 'New Delhi',
 'Pakistan': 'Islamabad',
 'Nepal': 'Kathmandu',
 'Bhutan': 'Thimphu',
 'China': 'Beijing',
 'Bangladesh': 'Dhaka'}

### File handling 

1. open()
2. close ()

“ r “, for reading.
“ w “, for writing.
“ a “, for appending.
“ r+ “, for both reading and writing.

In [80]:
file =open('text.txt','r')
content=file.read() # u can give arguments as numbers 
print(content)

hi hello i am from Text ...!!


In [78]:
with open('text.txt','r') as co:
    f=co.read()
    print(f)

hi hello i am from Text ...!!


In [31]:
for each in content  :
    pass
    #print(each)

In [63]:
# Python code to create a file 
file1= open('murugan.txt','w') 
file1.write("This is the write command ") 
file1.write("It allows us to write in") 
file1.close()

In [64]:
# Python code to illustrate append() mode 
file2 = open('murugan.txt','a') 
file2.write(" This will add this line") 
file2.close() 

In [103]:
cote=open('murugan.txt','r')
co=cote.read()
print(co)

This is the write command It allows us to write in This will add this line


In [105]:

f = open('murugan.txt','r')
filedata = f.read()
f.close()

newdata = filedata.replace("this","murugan")

f = open('murugan.txt','w')
f.write(newdata)
f.close()

In [ ]:
f1 = open('file1.txt', 'r')
f2 = open('file2.txt', 'w')
for line in f1:
    f2.write(line.replace('old_text', 'new_text'))
f1.close()
f2.close()

In [ ]:
# Python code to illustrate with() 
with open("file.txt") as file:   
    data = file.read()  
# do something with data 

In [ ]:
# Python code to illustrate with() alongwith write() 
with open("file.txt", "w") as f:  
    f.write("Hello World!!!") 

In [ ]:
import os;  
  
#rename file2.txt to file3.txt  
os.rename("file2.txt","file3.txt")  

In [ ]:
import os;  
  
#deleting the file named file3.txt   
os.remove("file3.txt")  

In [ ]:
import os;  
  
#creating a new directory with the name new  
os.mkdir("new") 

In [ ]:
import os;  
  
#removing the new directory   
os.rmdir("new") 

## Fucntions

In [25]:
def add():
    a=10
    b=20
    print(a+b)
print("Hi")
print("How r u ")
add()
print("Hello")
print("VIT")
add


Hi
How r u 
30
Hello
VIT


<function __main__.add()>

In [27]:
def add(a,b):
    print(a+b)
print("Hello")
add(10,20)

Hello
30


In [8]:
def hello():
  print("Hello World") 
  return("hello")

def hello_noreturn():
  print("Hello World none")
  
# Multiply the output of `hello()` with 2 
a=hello() 
print(a)
# (Try to) multiply the output of `hello_noreturn()` with 2 
hello_noreturn() 

Hello World
hello
Hello World none


In [10]:
def run():
  for x in range(10):
     if x == 2:
       return
  print("Run!")
  
run()

In [21]:
# Define `plus()` function to accept a variable number of arguments
def plus(*args):
    print(args)
    return sum(args)

# Calculate the sum
plus(1,4,5)

(1, 4, 5)


10

•	Filter
•	Map
•	Reduce
•	Decorators
•	Frozen set
•	Collections


## Lambda

In [91]:
# Lambda function 
#     SYNTAX :    lambda arguments: expression
#  This function can have any number of arguments but only one expression, which is evaluated and returned

def f1(a,b):
    print(a+b)

f1(5,5)


f=lambda x,y : x+y
f(5,5)

10


10

In [93]:
def cube(y): 
    return y*y*y; 
 
print(cube(7))


g = lambda x: x*x*x 
print(g(7)) 
  


343
343


## MAP , REDUCE, FILTER

In [6]:
l=[1,2,3]
l2=[]
def sq(a):
    return(a*2)
for i in l:
    l2.append(sq(i))
print(l2)


a=list(map (lambda x : x*2   , l))
print(a)

[2, 4, 6]


TypeError: 'list' object is not callable

In [4]:
# Python code to illustrate 
# filter() with lambda() 
li = [5, 7, 22, 97, 54, 62, 77, 23, 73, 61] 
final_list = list(filter(lambda x: (x%2 != 0) , li)) 
print(final_list)

TypeError: 'list' object is not callable

In [5]:
# Python code to illustrate  
# map() with lambda()  
# to get double of a list. 
li = [5, 7, 22, 97, 54, 62, 77, 23, 73, 61] 
final_list = list(map(lambda x: x*2 , li)) 
print(final_list)

TypeError: 'list' object is not callable

In [96]:
# Python code to illustrate  
# reduce() with lambda() 
# to get sum of a list 
from functools import reduce
li = [5, 8, 10, 20, 50, 100] 
sum = reduce((lambda x, y: x + y), li) 
print (sum)

# Here the result the list like (((((5+8)+10)+20)+50)+100).

193


## SET function

In [1]:
###Set Function 
a= set([1,2,3,4])
print(a)

{1, 2, 3, 4}


In [2]:
s1=set()
s2=set()
for i in range(1,8):
    s1.add(i)
for i in range (5,20):
    s2.add(i)
print(s1)
print(s2)

{1, 2, 3, 4, 5, 6, 7}
{5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19}


In [3]:
#Union and Intersection 
print(s1|s2)  ##Union

print(s1&s2)  ##Intersection

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19}
{5, 6, 7}


In [4]:
#s1.clear()

In [5]:
l=[1,2,3,1,3]
print(l)
l=set(l)
print(list(l))

[1, 2, 3, 1, 3]
[1, 2, 3]


In [19]:
sum([1,4,5])

10

In [22]:
from functools import reduce

my_list = [1,2,3,4,5,6,7,8,9,10]

# Use lambda function with `filter()`
filtered_list = list(filter(lambda x: (x*2 > 10), my_list))

# Use lambda function with `map()`
mapped_list = list(map(lambda x: x*2, my_list))

# Use lambda function with `reduce()`
reduced_list = reduce(lambda x, y: x+y, my_list)

print(filtered_list)
print(mapped_list)
print(reduced_list)

[6, 7, 8, 9, 10]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
55


In [23]:
# Python 3 code to demonstrate  
# working of assert  
# Application 
  
# initializing list of foods temperatures 
batch = [ 40, 26, 39, 30, 25, 21] 
  
# initializing cut temperature 
cut = 26
  
# using assert to check for temperature greater than cut 
for i in batch: 
    assert i >= 26, "Batch is Rejected"
    print (str(i) + " is O.K" )

40 is O.K
26 is O.K
39 is O.K
30 is O.K


AssertionError: Batch is Rejected

## OOPS concepts

In [1]:
class version1():
    def name(self):
        print("Name")
app=version1()
app.name()

Name


In [100]:
class version1:
    def name(self):
        print("Name Box")
    def age(self):
        print("age Box")
class version2(version1):
    def add(self):
        print("adress box")
if __name__=='__main__':
    app=version2()
    app.add()
    app.name()
    app.age()




adress box
Name Box
age Box


In [11]:
# Polymorphism 

class parrot:
    def fly(self):
        print("parrot can fly")
    def swim(self):
        print("parrot can not swim")
class penguin:
    def fly(self):
        print("penguin can not fly")
    def swim(self):
        print("penguin can swim")
        
# common interface
def flying_test(bird):
    bird.fly()
par=parrot()
pen=penguin()

flying_test(par)
flying_test(pen)

parrot can fly
penguin can not fly


In [32]:
#data encapsulation

class computer:
    def __init__(self):
        self.__maxprice=900
    def sell(self):
        print("selling price is ",self.__maxprice)
    def selmaxPrice(self,price):
        self.__maxprice=price
c=computer()
c.sell()

#change the price 
c.__maxprice=1000
c.sell()

# using setter function 
c.selmaxPrice(1000)
c.sell()

selling price is  900
selling price is  900
selling price is  1000


In [7]:
# Constructor (Initilization)
#create method :
class parrot:
    def __init__(self,name,age):  #artibutes
        self.name=name 
        self.age=age
        print("name is: ",self.name)
        print("age is: ",self.age)
    def sing(self):
        print("sing")
    def dance(self):
        print("dance")
bird=parrot('bird',10)

bird.sing()
bird.dance()
        
    

name is:  bird
age is:  10
sing
dance


In [5]:
import random
random.randint(1,100)

62

In [6]:

import numpy as np 
inp=3
r=np.random.rand(inp.shape(),4) 

AttributeError: 'int' object has no attribute 'shape'

In [41]:
class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
a=NeuralNetwork(3,2)
a.input

3

In [185]:
# Write Python3 code here  ,Uses of self parameter 
  
class car(): 
      
    # init method or constructor 
    def __init__(self, model, color): 
        self.model = model 
        self.color = color 
          
    def show(self): 
        print("Model is", self.model ) 
        print("color is", self.color ) 
          
# both objects have different self which  
# contain their attributes 
audi = car("audi a4", "blue") 
ferrari = car("ferrari 488", "green") 
  
audi.show()     # same output as car.show(audi) 
ferrari.show()  # same output as car.show(ferrari) 
  
# Behind the scene, in every instance method  
# call, python sends the instances also with 
# that method call like car.show(audi) 

Model is audi a4
color is blue
Model is ferrari 488
color is green


In [98]:
import numpy as np

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],4) 
        self.weights2   = np.random.rand(4,1)                 
        self.y          = y
        self.output     = np.zeros(self.y.shape)
        '''print(self.input)
        print()
        print(self.weights1)'''

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
        #print(self.output)
    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2


if __name__ == "__main__":
    X = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
    y = np.array([[0],[1],[1],[0]])
    nn = NeuralNetwork(X,y)
  
    for i in range(1500):
        nn.feedforward()
        nn.backprop()
    
    
    print(nn.output)
    print()
    print(nn.y - nn.output)

[[0.02427678]
 [0.98165625]
 [0.97753138]
 [0.02106706]]

[[-0.02427678]
 [ 0.01834375]
 [ 0.02246862]
 [-0.02106706]]


In [68]:
 inp = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
print(inp.shape[1])

a=np.random.rand(inp.shape[1],4) 
a

3


array([[0.40216904, 0.96341725, 0.54985949, 0.25161721],
       [0.09360005, 0.11534328, 0.31993782, 0.97146839],
       [0.50107061, 0.85709729, 0.88458149, 0.45469978]])

In [82]:
 a = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
b=np.random.rand(3,4)  
print(a)
print(b)
c=np.dot(a,b)
print(c)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0.07528181 0.69910328 0.76580821 0.14004023]
 [0.63577351 0.61482715 0.93174853 0.31571078]
 [0.91413848 0.69320577 0.20644607 0.6279208 ]]
[[0.91413848 0.69320577 0.20644607 0.6279208 ]
 [1.54991198 1.30803292 1.1381946  0.94363158]
 [0.98942028 1.39230905 0.97225428 0.76796103]
 [1.62519379 2.0071362  1.90400281 1.08367181]]


In [72]:
print(y.shape)
np.zeros(y.shape)

(4, 1)


array([[0.],
       [0.],
       [0.],
       [0.]])

In [103]:
5/2


2

In [102]:
5//2

2

In [115]:
class MyClass:
 Greeting = ""
 def __init__(self, Name="there"):
  self.Greeting = Name + "!"
 def SayHello(self):
  print("Hello {0}".format(self.Greeting))
a=MyClass()
a.Greeting

'there!'

In [162]:
# Python code to demonstrate 
# to get characters from string 
import re 
  
# initialising string 
ini_string = "123()#$ABGFDabcjw"
ini_string2 = "abceddfgh"
  
# printing strings 
print ("initial string : ", ini_string, ini_string2) 
  
# code to find characters in string 
res1 = " ".join(re.split("[^a-zA-Z]*", ini_string)) 
res2 = " ".join(re.split("[^a-zA-Z]*", ini_string2)) 
  
# printing resultant string 
print ("first string result: ", str(res1)) 
print ("second string result: ", str(res2)) 


initial string :  123()#$ABGFDabcjw abceddfgh
first string result:   ABGFDabcjw
second string result:  abceddfgh


/home/sands/anaconda3/lib/python3.6/re.py:212: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)


In [190]:
class art:
    def add(self):
        print("hello")
a=art()
a.add()

hello


In [4]:
f=lambda x,y : x+y
f(5,5)

10

In [16]:
l=[1,2,3]
a=list(map (lambda x : x*2   , l))
print(a)

[2, 4, 6]


In [19]:
l=[1,2,3,4,5,6,7,8,9]

a=list(filter(lambda x: x%2==0 , l))
print(a)

[2, 4, 6, 8]


## Modules

In [10]:
from userlib import greeting ,add
greeting()
add(5,5)

I am from another module
10


In [25]:
f= open ("text.txt",'r')
file= f.read()
print(file)

hi hello i am from Text ...!!


In [35]:
with open ("text.txt", 'r') as fp:
    fi=fp.read()
print(fi)

hi hello i am from Text ...!!


In [38]:
def argg(*args):
    print(args)
argg("Murugan", "is", "a", "Good")

('Murugan', 'is', 'a', 'Good')


In [55]:
def argg(*args):
    for i in args:
        print(i)
argg("Murugan", "is", "a", "Good")

Murugan
is
a
Good


In [56]:
# Python code to demonstrate 
# **kwargs for dynamic + named arguments 
def fn(**kwargs):  
    for emp, age in kwargs.items(): 
        print ("%s's age is %s." %(emp, age)) 
    
fn(John=25, Kalley=22, Tom=32)

John's age is 25.
Kalley's age is 22.
Tom's age is 32.


## Errror Handling

In [7]:
a = int(input("Enter a:"))  
b = int(input("Enter b:"))  
c = a/b;  
print("a/b = %d"%c) 

Enter a:10
Enter b:0


ZeroDivisionError: division by zero

In [ ]:
#IndexError, name error , zerodivision error , keyboard interrupt,  IO error , indentation error 

In [8]:
number = int(input("Enter a number between 1 - 10"))

print ("you entered number", number)

Enter a number between 1 - 10gvgv


ValueError: invalid literal for int() with base 10: 'gvgv'

In [9]:
try:
        n = input("Please enter an integer: ")
        n = int(n)
except ValueError:
        print("No valid integer! Please try again ...")

Please enter an integer: ghkg
No valid integer! Please try again ...


In [11]:
try:  
    a = int(input("Enter a:"))  
    b = int(input("Enter b:"))  
    c = a/b;  
    print("a/b = %d"%c)  
except Exception:  
    print("can't divide by zero")  
else:  
    print("Hi I am else block") 

Enter a:5
Enter b:0
can't divide by zero


In [11]:
# Python program to handle simple runtime error 
  
a = [1, 2, 3] 
try:  
    print ("Second element = %d"%(a[1])) 
  
    # Throws error since there are only 3 elements in array 
    print ("Fourth element = %d"%(a[3]))  
  
except IndexError: 
    print ("An error occurred")

Second element = 2
An error occurred


In [11]:
try:
        n = input("Please enter an integer: ")
        n = int(n)
except ValueError:
        print("No valid integer! Please try again ...")

Please enter an integer: gcg
No valid integer! Please try again ...


In [4]:
try:  
    a = int(input("Enter a?"))  
    b = int(input("Enter b?"))  
    if b is 0:  
        raise ArithmeticError;  
    else:  
        print("a/b = ",a/b)  
except ArithmeticError:  
    print("The value of b can't be 0") 

Enter a?3
Enter b?5
a/b =  0.6


In [3]:
try:
  print("Hello")
except:
  print("Something went wrong")
else:
  print("Nothing went wrong")

Hello
Nothing went wrong


In [4]:
try:
  print(x)
except:
  print("Something went wrong")
finally:
  print("The 'try except' is finished")

Something went wrong
The 'try except' is finished


In [5]:
try:
  f = open("demofile.txt")
  f.write("Lorum Ipsum")
except:
  print("Something went wrong when writing to the file")
finally:
  f.close()

Something went wrong when writing to the file


NameError: name 'f' is not defined

## Threading concept 

The thread is nothing but a process or task. The main benefit of using thread is you can execute multiple tasks at the same time. In this Python Threading Example, we will see how do we create Threads and work with parallel execution in python.

In [14]:
import time
 
#First Method
def greet_them(people):
    for person in people:
        print("Hello Dear " + person + ". How are you?")
        time.sleep(0.5)
 
#Second Method
def assign_id(people):
    i = 1
    for person in people:
        print("Hey! {}, your id is {}.".format(person, i))
        i += 1
        time.sleep(0.5)
 
 
people = ['Murugan', 'Dinesh', 'Rajesh', 'sugu', 'bala']
 
t = time.time()
 
greet_them(people)
assign_id(people)
 
print("Woaahh!! My work is finished..")
print("I took " + str(time.time() - t))

Hello Dear Murugan. How are you?
Hello Dear Dinesh. How are you?
Hello Dear Rajesh. How are you?
Hello Dear sugu. How are you?
Hello Dear bala. How are you?
Hey! Murugan, your id is 1.
Hey! Dinesh, your id is 2.
Hey! Rajesh, your id is 3.
Hey! sugu, your id is 4.
Hey! bala, your id is 5.
Woaahh!! My work is finished..
I took 5.025583267211914


First, let’s understand some basics about the thread. So whenever you want to create a thread in python, you have to do the following thing.

Step #1: Import threading module. You have to module the standard python module threading if you are going to use thread in your python code.

Step #2: We create a thread as threading.Thread(target=YourFunction, args=ArgumentsToTheFunction).

Step #3: After creating the thread, we start it using the start() function.

Step #4: We also call the join() function to stop the thread after completion of the task.

So, now let’s modify our code, and call the methods in their separate threads. Feeling Excited? 

In [15]:
import time
import threading
 
# Python Threading Example for Beginners
# First Method
def greet_them(people):
    for person in people:
        print("Hello Dear " + person + ". How are you?")
        time.sleep(0.5)
 
 
# Second Method
def assign_id(people):
    i = 1
    for person in people:
        print("Hey! {}, your id is {}.".format(person, i))
        i += 1
        time.sleep(0.5)
 
 
people = ['Murugan', 'Dinesh', 'Rajesh', 'sugu', 'bala']
 
t = time.time()
 
#Created the Threads
t1 = threading.Thread(target=greet_them, args=(people,))
t2 = threading.Thread(target=assign_id, args=(people,))
 
#Started the threads
t1.start()
t2.start()
 
#Joined the threads
t1.join()
t2.join()
 
print("Woaahh!! My work is finished..")
print("I took " + str(time.time() - t))


Hello Dear Murugan. How are you?Hey! Murugan, your id is 1.

Hey! Dinesh, your id is 2.Hello Dear Dinesh. How are you?

Hey! Rajesh, your id is 3.Hello Dear Rajesh. How are you?

Hey! sugu, your id is 4.Hello Dear sugu. How are you?

Hey! bala, your id is 5.Hello Dear bala. How are you?

Woaahh!! My work is finished..
I took 2.5671463012695312


In [1]:
class x():
    def run(self):
        for i in range (1,50):
            print(i)

class y():
    def run(self):
        for y in range (1,101):
            print(y)
x1=x()
y1=y()
x1.run()
y1.run()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [8]:
### threading concept 

import threading 

class x(threading.Thread):
    def run(self):
        for i in range (1,50):
            print(i)

class y(threading.Thread):
    def run(self):
        for y in range (1,101):
            print(y)
x1=x()
y1=y()
x1.start()
y1.start()

1
2
3
4
5
6
7
8
9
10
11
12
13
114
15
16
17
18
19

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [8]:
#!/usr/bin/python
import threading
import thread
import time
from subprocess import call

# Define a function for the thread
def print_time( threadName, delay):
   count = 0
   while count < 10:
      time.sleep(delay)
      count += 1
      #print "%s: %s" % ( threadName, time.ctime(time.time()) )
      print("abi")
      #call(["python", "hi.py"])
def print_tim( threadName, delay):
   count = 0
   while count < 10:
      time.sleep(delay)
      count += 1
      #print "%s: %s" % ( threadName, time.ctime(time.time()) )
      print ("ammu")
      #call(["python", "hello.py"])
# Create two threads as follows
try:
   thread.start_new_thread( print_time, ("Thread-1", 1, ) )
   thread.start_new_thread( print_tim, ("abi", 1, ) )
except:
   print ("Error: unable to start thread")

while 1:
   pass


ModuleNotFoundError: No module named 'thread'

In [86]:
import requests
import json

send_url = "http://api.ipstack.com/103.81.238.70?access_key=fd6343bfa5930cc9248b7e4a28ee7d0a"
geo_req = requests.get(send_url)
geo_json = json.loads(geo_req.text)
latitude = geo_json['latitude']
longitude = geo_json['longitude']
city = geo_json['city']

In [87]:
print(latitude)
print(longitude)
print(city) 

13.087
80.2456
Chennai


In [8]:
l=['a','d','a','e','f','d']
nl=list(dict.fromkeys(l))

In [9]:
nl

['a', 'd', 'e', 'f']

## DateTime 

In [7]:
from datetime import date

from datetime import time

from datetime import datetime

In [10]:
from datetime import date

print (date.today())
print("my today date is",date.today())

2019-09-04
my today date is 2019-09-04


In [95]:
today=date.today()
print(today)
print(today.day)
print(today.month)
print(today.year)
weekday=today.weekday()
print(weekday)

2019-09-05
5
9
2019
3


TypeError: unsupported operand type(s) for -: 'datetime.date' and 'int'

In [72]:
print(datetime.now())

2019-09-05 19:12:08.189462


In [22]:
#current time 
time=datetime.now()
print(time)

2019-09-04 06:59:22.475993


In [24]:
#data formatting

now=datetime.now()
print(now)

2019-09-04 07:02:27.653686


In [ ]:
#   [(%y/%Y – Year), (%a/%A- weekday), (%b/%B- month), (%d - day of month)] 

In [33]:
print(now.strftime("%Y")) #print(now.strftime(%Y))
print(now.strftime("%A"))
print(now.strftime("%B"))
print(now.strftime("%d"))

2019
Wednesday
September
04


In [34]:
print(now.strftime("%a,%D,%B,%Y"))

Wed,09/04/19,September,2019


In [39]:
from datetime import date
from datetime import time
from datetime import datetime
def main():
    ##DATETIME OBJECTS
    #Get today's date from datetime class
    today=datetime.now()
    #print (today)
    # Get the current time
    #t = datetime.time(datetime.now())
    #print "The current time is", t
    #weekday returns 0 (monday) through 6 (sunday)
    wd=date.weekday(today)
    #Days start at 0 for monday
    days= ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
    print("Today is day number %d" % wd)
    print("which is a " + days[wd])

if __name__== "__main__":
    main()

Today is day number 2
which is a wednesday


%C- indicates the local date and time
%x- indicates the local date
%X- indicates the local time

In [37]:
now=datetime.now()
print(now.strftime("%C"))
print(now.strftime("%x"))
print(now.strftime("%X"))

20
09/04/19
07:09:42


In [38]:
#
#Example file for formatting time and date output
#
from datetime import datetime
def main():
   #Times and dates can be formatted using a set of predefined string
   #Control codes
      now= datetime.now() #get the current date and time
      #%c - local date and time, %x-local's date, %X- local's time
      print(now.strftime("%c"))
      print(now.strftime("%x"))
      print(now.strftime("%X"))
##### Time Formatting ####
      #%I/%H - 12/24 Hour, %M - minute, %S - second, %p - local's AM/PM
      print(now.strftime("%I:%M:%S %p")) # 12-Hour:Minute:Second:AM
      print(now.strftime("%H:%M")) # 24-Hour:Minute

if __name__== "__main__":
    main()

Wed Sep  4 07:11:26 2019
09/04/19
07:11:26
07:11:26 AM
07:11


#### Assertions are simply boolean expressions that checks if the conditions return true or not. If it is true, the program does nothing and move to the next line of code.
#### However, if it's false, the program stops and throws an error.It is also a debugging tool as it brings the program on halt as soon as any error is occurred and shows on which point of the program error has occurred.

In [43]:
x = "hello"

#if condition returns True, then nothing happens:
assert x == "hello"

#if condition returns False, AssertionError is raised:
assert x == "goodbye"

AssertionError: 

In [44]:
num=int(input('Enter a number: '))
assert num>=0
print('You entered: ', num)

Enter a number: 1
You entered:  1


In [41]:
# Python 3 code to demonstrate  
# working of assert  
# Application 
  
# initializing list of foods temperatures 
batch = [ 40, 26, 39, 30, 25, 21,27] 
  
# initializing cut temperature 
cut = 26
  
# using assert to check for temperature greater than cut 
for i in batch: 
    assert i >= 26, "Batch is Rejected"
    print (str(i) + " is O.K" )

40 is O.K
26 is O.K
39 is O.K
30 is O.K


AssertionError: Batch is Rejected

In [ ]:
import tkinter as tk 
r = tk.Tk() 
r.title('Counting Seconds') 
button = tk.Button(r, text='Stop', width=25, command=r.destroy) 
button.pack() 
r.mainloop() 

In [10]:
from tkinter import *
master = Tk() 
Label(master, text='First Name').grid(row=0) 
Label(master, text='Last Name').grid(row=1) 
e1 = Entry(master) 
e2 = Entry(master) 
e1.grid(row=0, column=1) 
e2.grid(row=1, column=1) 
mainloop() 

## Regular expression

In [1]:
import re

#Check if the string starts with "The" and ends with "paper":

txt = "The news paper"
x = re.search("^The.*paper$", txt)
print(x)
if (x):
  print("YES! We have a match!")
else:
  print("No match")

<_sre.SRE_Match object; span=(0, 14), match='The news paper'>
YES! We have a match!


In [85]:
import re

str = "The news paper paper"
x = re.findall("pa", str)
print(x)

['pa', 'pa']


In [86]:
import re

str = "The news paper"
x = re.findall("Portugal", str)
print(x)

[]


In [87]:
import re

str = "The news paper"
x = re.search("\s", str)

print("The first white-space character is located in position:", x.start())

The first white-space character is located in position: 3


In [49]:
import re

str = "The rain in Spain"
x = re.search("Portugal", str)
print(x)

None


In [50]:
result=re.split(r'y','Analytics')
result

['Anal', 'tics']

In [51]:
import re

str = "The rain in Spain"
x = re.split("\s", str)  #it will split the word, when white space is there 
print(x)

['The', 'rain', 'in', 'Spain']


In [52]:
import re

str = "The rain in Spain"
x = re.split("\s", str, 1)
print(x)

['The', 'rain in Spain']


In [53]:
import re

str = "The rain in Spain"
x = re.sub("\s", "9", str)  # sub is replace 
print(x)

The9rain9in9Spain


In [54]:
import re
str = "The rain in Spain"
x = re.search(r"\bS\w+", str)
print(x.span())

(12, 17)


In [97]:
l=[False,True,True]
a=any(l)
print(a)

True


### import math, os, sys

In [57]:
# importing built-in module math 
import math 
  
# using square root(sqrt) function contained  
# in math module 
print (math.sqrt(25)  )
  
# using pi function contained in math module 
print math.pi  
  
# 2 radians = 114.59 degreees 
print math.degrees(2)  
  
# 60 degrees = 1.04 radians 
print math.radians(60)  
  
# Sine of 2 radians 
print math.sin(2)  
  
# Cosine of 0.5 radians 
print math.cos(0.5)  
  
# Tangent of 0.23 radians 
print math.tan(0.23) 
  
# 1 * 2 * 3 * 4 = 24 
print math.factorial(4)  
  
  
# importing built in module random 
import random 
  
# printing random integer between 0 and 5 
print random.randint(0, 5)  
  
# print random floating point number between 0 and 1 
print random.random()  
  
# random number between 0 and 100 
print random.random() * 100 
  
List = [1, 4, True, 800, "python", 27, "hello"] 
  
# using choice function in random module for choosing  
# a random element from a set such as a list 
print random.choice(List) 
  
  
# importing built in module datetime 
import datetime 
from datetime import date 
import time 
  
# Returns the number of seconds since the 
# Unix Epoch, January 1st 1970 
print time.time()  
  
# Converts a number of seconds to a date object 
print date.fromtimestamp(454554)  

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(math.pi)? (<ipython-input-57-7b869c32f676>, line 9)

In [88]:
import sys
sys.path

['',
 'C:\\Users\\Murugan\\Anaconda3\\python36.zip',
 'C:\\Users\\Murugan\\Anaconda3\\DLLs',
 'C:\\Users\\Murugan\\Anaconda3\\lib',
 'C:\\Users\\Murugan\\Anaconda3',
 'C:\\Users\\Murugan\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\Murugan\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\Murugan\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Murugan\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Murugan\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Murugan\\.ipython']

In [89]:
sys.version

'3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]'

In [92]:
import sys

#print("Coming through stdout")

# stdout is saved
save_stdout = sys.stdout
print(save_stdout)

   ### COLLECTIONS

In [59]:
                                        #deque

from collections import deque
list = ["a","b","c"]
deq = deque(list)
print(deq)

deque(['a', 'b', 'c'])


In [60]:
deq.append("d")
deq.appendleft("e")
print(deq)

deque(['e', 'a', 'b', 'c', 'd'])


In [61]:
deq.pop()
deq.popleft()
print(deq)

deque(['a', 'b', 'c'])


In [62]:
                                        #Counter 

from collections import Counter
list = [1,2,3,4,1,2,6,7,3,8,1]
Counter(list)

Counter({1: 3, 2: 2, 3: 2, 4: 1, 6: 1, 7: 1, 8: 1})

In [63]:
list = [1,2,3,4,1,2,6,7,3,8,1]
cnt = Counter(list)
print(cnt[1])

3


In [94]:
                                        # OrderedDict

colours =  {"Red" : 198, "Blue" : 160, "Green" : 170}
for key, value in colours.items():
    print(key, value)

Red 198
Blue 160
Green 170


In [66]:
from collections import OrderedDict

colours = OrderedDict([("Red", 198), ("Green", 170), ("Blue", 160)])
for key, value in colours.items():
    print(key, value)

Red 198
Green 170
Blue 160


### Python Membership (in, not in) and Identity Operators (is, is not)

In [3]:
a = 10
b = 20
list = [1, 2, 3, 4, 5 ];

if ( a in list ):
   print ("Line 1 - a is available in the given list")
else:
   print ("Line 1 - a is not available in the given list")

if ( b not in list ):
   print ("Line 2 - b is not available in the given list")
else:
   print ("Line 2 - b is available in the given list")

Line 1 - a is not available in the given list
Line 2 - b is not available in the given list


In [68]:
# Python program to illustrate the use  
# of 'is' identity operator 
x = 5
if (type(x) is int): 
    print ("true") 
else: 
    print ("false") 

true


In [1]:
# Python program to illustrate the  
# use of 'is not' identity operator 
x = 5.2
if (type(x) is not int): 
    print ("true") 
else: 
    print ("false")

true


In [70]:
###        http://www.mysqltutorial.org/python-mysql/

###        https://www.datacamp.com/community/tutorials/mysql-python