In [1]:
print("Hello VIT ")

Hello VIT 


In [2]:
a=10
b=20
c=a+b
print(c)

30


In [3]:
type(a)

int

In [4]:
b=10.5
type(b)

float

In [5]:
a="Murugan"
type(a)

str

In [6]:
a=10
b=20
c=a+b
print(c)

30


In [7]:
c=int(input("Enter 1st number "))


Enter 1st number 10


In [8]:
type(a)

int

In [9]:
a=int(input("Enter 1st number "))
b=int(input("Enter 2nd number "))
print(a+b)

Enter 1st number 20
Enter 2nd number 20
40


In [10]:
a=int(input("Enter any number "))
if a==10:
    print("sucess")
else:
    print("failure")

Enter any number 10
sucess


In [11]:

while True:
    a=int(input("Enter any number "))
    if a==10:
        print("sucess")
        break
    else:
        print("failure")

Enter any number 10
sucess


In [12]:
for i in range(2):
    a=int(input("Enter any number "))
    if a==10:
        print("sucess")
    else:
        print("failure")

Enter any number 10
sucess
Enter any number 10
sucess
Enter any number 20
failure
Enter any number 20
failure
Enter any number 20
failure


In [13]:
a="Murugan"
print(a)

Murugan


In [14]:
a[0:3]

'Mur'

In [15]:
a[4:7]

'gan'

In [16]:
a[0:7:2]

'Mrgn'

In [17]:
a[::-1]

'naguruM'

In [18]:
l=["murugan",8,9,'a',10]
print(l)

['murugan', 8, 9, 'a', 10]


In [19]:
l[0:3]

['murugan', 8, 9]

In [20]:
len(l)

5

In [21]:
l

['murugan', 8, 9, 'a', 10]

In [22]:
l.append("vit")

In [23]:
print(l)

['murugan', 8, 9, 'a', 10, 'vit']


In [24]:
l.insert(2,"Vit")

In [25]:
l

['murugan', 8, 'Vit', 9, 'a', 10, 'vit']

In [26]:
l.remove("murugan")

print(l)

In [27]:
print(l)

[8, 'Vit', 9, 'a', 10, 'vit']


In [28]:
l.append("Vit")

In [29]:
l

[8, 'Vit', 9, 'a', 10, 'vit', 'Vit']

In [30]:
l.count("Vit")

2

In [31]:
def add():
    a=10
    b=20
    print(a+b)
print("Hi")
print("How r u ")
add()
print("Hello")
print("VIT")
add


Hi
How r u 
30
Hello
VIT


<function __main__.add()>

In [32]:
def add(a,b):
    print(a+b)
print("Hello")
add(10,20)

Hello
30


In [33]:
class version1():
    def name(self):
        print("Name")
app=version1()
app.name()

Name


In [34]:
class version1:
    def name(self):
        print("Name Box")
    def age(self):
        print("age Box")
class version2(version1):
    def add(self):
        print("adress box")
if __name__=='__main__':
    app=version2()
    app.add()
    app.name()
    app.age()




adress box
Name Box
age Box


In [36]:
class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
a=NeuralNetwork(3,2)
a.input

3

In [37]:
# Write Python3 code here  ,Uses of self parameter 
  
class car(): 
      
    # init method or constructor 
    def __init__(self, model, color): 
        self.model = model 
        self.color = color 
          
    def show(self): 
        print("Model is", self.model ) 
        print("color is", self.color ) 
          
# both objects have different self which  
# contain their attributes 
audi = car("audi a4", "blue") 
ferrari = car("ferrari 488", "green") 
  
audi.show()     # same output as car.show(audi) 
ferrari.show()  # same output as car.show(ferrari) 
  
# Behind the scene, in every instance method  
# call, python sends the instances also with 
# that method call like car.show(audi) 

Model is audi a4
color is blue
Model is ferrari 488
color is green


In [38]:
import numpy as np

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],4) 
        self.weights2   = np.random.rand(4,1)                 
        self.y          = y
        self.output     = np.zeros(self.y.shape)
        '''print(self.input)
        print()
        print(self.weights1)'''

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
        #print(self.output)
    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2


if __name__ == "__main__":
    X = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
    y = np.array([[0],[1],[1],[0]])
    nn = NeuralNetwork(X,y)
  
    for i in range(1500):
        nn.feedforward()
        nn.backprop()
    
    
    print(nn.output)
    print()
    print(nn.y - nn.output)

[[0.00961001]
 [0.97429788]
 [0.97348766]
 [0.02989575]]

[[-0.00961001]
 [ 0.02570212]
 [ 0.02651234]
 [-0.02989575]]


In [39]:
 inp = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
print(inp.shape[1])

a=np.random.rand(inp.shape[1],4) 
a

3


array([[2.95604558e-01, 7.81130242e-01, 2.96369016e-01, 8.40474455e-01],
       [9.54365438e-02, 3.26663052e-01, 6.52518124e-04, 5.82613431e-01],
       [4.78495639e-01, 9.49911874e-01, 5.59040131e-01, 6.26168725e-01]])

In [40]:
 a = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
b=np.random.rand(3,4)  
print(a)
print(b)
c=np.dot(a,b)
print(c)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0.4131783  0.57325472 0.03085501 0.41619416]
 [0.32046004 0.3832862  0.42209415 0.14602577]
 [0.83960528 0.26122904 0.30306521 0.15440615]]
[[0.83960528 0.26122904 0.30306521 0.15440615]
 [1.16006533 0.64451524 0.72515936 0.30043192]
 [1.25278358 0.83448376 0.33392022 0.57060031]
 [1.57324362 1.21776996 0.75601437 0.71662608]]


In [41]:
print(y.shape)
np.zeros(y.shape)

(4, 1)


array([[0.],
       [0.],
       [0.],
       [0.]])

In [42]:
5/2


2.5

In [43]:
5//2

2

In [44]:
class MyClass:
 Greeting = ""
 def __init__(self, Name="there"):
  self.Greeting = Name + "!"
 def SayHello(self):
  print("Hello {0}".format(self.Greeting))
a=MyClass()
a.Greeting

'there!'

In [45]:
a="My name is 7 Murugan 8 and good "
b=a.split()
print(b)

['My', 'name', 'is', '7', 'Murugan', '8', 'and', 'good']


In [46]:
[int(i) for i in b if i.isdigit()]
   

[7, 8]

In [47]:
c=[]
for i in b :
    if i.isdigit():
        c.append(int(i))
print(c)

[7, 8]


In [50]:
a=ini_string = "123()#$ABGFDabcjw"
#isalpha()
c=[]
for i in a:
    if i.isalpha():
#isalpha()
c=[]
c.append(str(i))
print(c)
a="".join(c)
print(str(a))

IndentationError: expected an indented block (<ipython-input-50-4eeefb57e37b>, line 7)

In [51]:
def sqr(a):
    b=a**2
    return b
l=[1,2,3]
c=map(sqr,l)
print(list(c))

[1, 4, 9]


In [52]:
print("Murugan")
print("\nsukumar")

Murugan

sukumar


In [53]:
dic ={
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
dic.items()

dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964)])

In [54]:
f=lambda a,b:a+b

f(2,3)

5

In [55]:
def sqr(a):
    b=a**2
    return b

l=[1,2,3,4]
c=map(sqr,l)
print(list(c))

[1, 4, 9, 16]


In [56]:
l=[1,2,3,4]
c=map((lambda l:l**2), l)
print(list(c))

[1, 4, 9, 16]


In [57]:
###Set Function 
a= set([1,2,3,4])
print(a)

{1, 2, 3, 4}


In [58]:
s1=set()
s2=set()
for i in range(1,8):
    s1.add(i)
for i in range (5,20):
    s2.add(i)
print(s1)
print(s2)

{1, 2, 3, 4, 5, 6, 7}
{5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19}


In [59]:
#Union and Intersection 
print(s1|s2)  ##Union

print(s1&s2)  ##Intersection 


{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19}
{5, 6, 7}


In [60]:
s1.clear()

In [61]:
##Multiple arguments 

def myFun(*args):  
    for arg in args:  
        print (arg) 
myFun("hello","how" ,"are" , "you" )

hello
how
are
you


In [62]:
## Keyword Argumetns 

def myFun(**kwargs):  
    for key, value in kwargs.items(): 
        print ("%s == %s" %(key, value)) 
  
# Driver code 
myFun(first ='Hi', mid ='Hello', last='How are You ')

first == Hi
mid == Hello
last == How are You 


In [63]:
while 1:
    a=int(input("Enter A number : "))
    if a<100:

        if a>50:
                print("A is 50 100 ..")
                break
        else :
                print("A is less than 50  ..")
                pass
    print("Continue excuted ")
    print("continue Excuted ")

print("A is in between 50-100 Break excuted ")
    
    

Enter A number : 49
A is less than 50  ..
Continue excuted 
continue Excuted 
Enter A number : 51
A is 50 100 ..
A is in between 50-100 Break excuted 


In [72]:
file = open('hi.txt', 'r') 
# This will print every line one by one in the file 
for each in file: 
    print (each) 



Hello World!!!


In [67]:
# Python code to create a file 
file = open('hello.txt','w') 
file.write("This is the write command") 
file.write("It allows us to write in a particular file") 
file.close() 

In [68]:
# Python code to illustrate append() mode 
file = open('hi.txt','a') 
file.write("This will add this line") 
file.close()

In [70]:
# Python code to illustrate with() 
with open("hello.txt") as file:   
    data = file.read()  
# do something with data 
print(data)

This is the write commandIt allows us to write in a particular file


In [71]:
# Python code to illustrate with() alongwith write() 
with open("hi.txt", "w") as f:  
    f.write("Hello World!!!")  

In [3]:
# Python code to demonstrate 
# to get characters from string 
import re 
  
# initialising string 
ini_string = "123()#$ABGFDabcjw"
ini_string2 = "abceddfgh"
  
# printing strings 
print ("initial string : ", ini_string, ini_string2) 
  
# code to find characters in string 
res1 = " ".join(re.split("[^a-zA-Z]*", ini_string)) 
res2 = " ".join(re.split("[^a-zA-Z]*", ini_string2)) 
  
# printing resultant string 
print ("first string result: ", str(res1)) 
print ("second string result: ", str(res2)) 


initial string :  123()#$ABGFDabcjw abceddfgh
first string result:   ABGFDabcjw
second string result:  abceddfgh


/home/sands/anaconda3/lib/python3.6/re.py:212: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)


In [35]:
activation = lambda x: 1.0/(1.0 + np.exp(-x)) # sigmoid function 
input = np.random.randn(3, 1) 
hidden_1 = activation(np.dot(W1, input) + b1) 
hidden_2 = activation(np.dot(W2, hidden_1) + b2) 
output = np.dot(W3, hidden_2) + b3 

NameError: name 'W1' is not defined